"""added new fields

Revision ID: d8da2dc7755b
Revises: 11916646f61c
Create Date: 2025-04-13 14:41:46.160770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = 'd8da2dc7755b'
down_revision: Union[str, None] = '11916646f61c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('validations', sqlmodel.sql.sqltypes.AutoString()))
    op.add_column('exercise', sa.Column('configurations', sqlmodel.sql.sqltypes.AutoString()))
    op.add_column('templatevm', sa.Column('hostname', sqlmodel.sql.sqltypes.AutoString(),))
    op.add_column('templatevm', sa.Column('gns3_project_id', sqlmodel.sql.sqltypes.AutoString()))
    op.add_column('workvm', sa.Column('hostname', sqlmodel.sql.sqltypes.AutoString()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workvm', 'hostname')
    op.drop_column('templatevm', 'gns3_project_id')
    op.drop_column('templatevm', 'hostname')
    op.drop_column('exercise', 'configurations')
    op.drop_column('exercise', 'validations')
    # ### end Alembic commands ###
