---
  up202001001:
    groups:
    - linux
    hostname: 192.168.57.145
    password: admredes23
    username: up

  up202001002:
    groups:
    - linux
    hostname: 192.168.57.139
    password: admredes23
    username: up

  teacher:
    groups:
    - linux
    hostname: 192.168.57.144
    password: admredes23
    username: up